// v1.6.1-rc.9 — GENERATED by tools/analyze_user_fills.py.
// DO NOT EDIT: re-run the analyzer to update.
// Source of truth = tools/user_fills/*.wav (20 intensity-graded
// drum fills supplied by the user). Each fill is parsed into our
// 8-lane canonical MIDI (kick=36 snare=38 hat=42 lowTom=43
// highTom=48 lcrash=49 ride=51 rcrash=57) and exposed as the
// fill library the FILL cycler rotates through and the auto-fill
// scheduler drops on bar 8 of every 8-bar phrase.
#pragma once

#include "MidiPattern.h"

#include <string_view>
#include <vector>

namespace aidrum
{
    struct BuiltInFill
    {
        std::string_view name;
        int             intensity;  // 10..100
        MidiPattern     pattern;
    };

    inline const std::vector<BuiltInFill>& fillLibrary()
    {
        static const std::vector<BuiltInFill> kFills = [] {
            std::vector<BuiltInFill> v;
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.328f, 0.0, 0.25 });
                p.notes.push_back ({ 38, 0.522f, 0.5, 0.25 });
                p.notes.push_back ({ 42, 0.462f, 0.75, 0.25 });
                p.notes.push_back ({ 48, 0.632f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.476f, 1.5, 0.25 });
                v.push_back ({ "Fill 10 Intensity 1", 10, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 36, 0.492f, 0.0, 0.25 });
                p.notes.push_back ({ 38, 0.422f, 0.25, 0.25 });
                p.notes.push_back ({ 43, 0.516f, 0.5, 0.25 });
                p.notes.push_back ({ 48, 0.661f, 0.75, 0.25 });
                p.notes.push_back ({ 43, 0.53f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.439f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.507f, 1.5, 0.25 });
                p.notes.push_back ({ 42, 0.658f, 1.75, 0.25 });
                v.push_back ({ "HR Fill 10 Intensity 1", 10, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.33f, 0.0, 0.25 });
                p.notes.push_back ({ 42, 0.691f, 0.5, 0.25 });
                p.notes.push_back ({ 43, 0.532f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.456f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.502f, 1.5, 0.25 });
                p.notes.push_back ({ 36, 0.487f, 1.75, 0.25 });
                v.push_back ({ "Fill 20 Intensity 1", 20, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.596f, 0.25, 0.25 });
                p.notes.push_back ({ 42, 0.585f, 0.75, 0.25 });
                p.notes.push_back ({ 43, 0.581f, 1.25, 0.25 });
                p.notes.push_back ({ 38, 0.547f, 1.75, 0.25 });
                v.push_back ({ "HR Fill 20 Intensity 1", 20, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.33f, 0.0, 0.25 });
                p.notes.push_back ({ 42, 0.693f, 0.5, 0.25 });
                p.notes.push_back ({ 43, 0.534f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.435f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.509f, 1.5, 0.25 });
                p.notes.push_back ({ 36, 0.472f, 1.75, 0.25 });
                v.push_back ({ "Fill 30 Intensity 1", 30, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.646f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.678f, 0.125, 0.25 });
                p.notes.push_back ({ 43, 0.503f, 0.375, 0.25 });
                p.notes.push_back ({ 48, 0.543f, 0.625, 0.25 });
                p.notes.push_back ({ 43, 0.651f, 1.125, 0.25 });
                p.notes.push_back ({ 48, 0.562f, 1.625, 0.25 });
                p.notes.push_back ({ 38, 0.58f, 1.75, 0.25 });
                v.push_back ({ "HR Fill 30 Intensity 1", 30, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.335f, 0.25, 0.25 });
                p.notes.push_back ({ 48, 0.584f, 0.75, 0.25 });
                p.notes.push_back ({ 43, 0.452f, 1.25, 0.25 });
                p.notes.push_back ({ 36, 0.445f, 1.5, 0.25 });
                p.notes.push_back ({ 38, 0.564f, 1.75, 0.25 });
                v.push_back ({ "FIll 40 Intensity 1", 40, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.603f, 0.125, 0.25 });
                p.notes.push_back ({ 42, 0.578f, 0.5, 0.25 });
                p.notes.push_back ({ 38, 0.579f, 0.625, 0.25 });
                p.notes.push_back ({ 43, 0.556f, 1.125, 0.25 });
                p.notes.push_back ({ 43, 0.56f, 1.5, 0.25 });
                p.notes.push_back ({ 43, 0.589f, 1.625, 0.25 });
                p.notes.push_back ({ 38, 0.587f, 1.75, 0.25 });
                v.push_back ({ "HR FIll 40 Intensity 1", 40, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 43, 0.456f, 0.0, 0.25 });
                p.notes.push_back ({ 36, 0.533f, 0.5, 0.25 });
                p.notes.push_back ({ 36, 0.506f, 0.75, 0.25 });
                p.notes.push_back ({ 43, 0.632f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.516f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.605f, 1.5, 0.25 });
                p.notes.push_back ({ 38, 0.589f, 1.75, 0.25 });
                v.push_back ({ "Fill 50 Intensity 1", 50, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 43, 0.591f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.48f, 0.375, 0.25 });
                p.notes.push_back ({ 43, 0.551f, 0.625, 0.25 });
                p.notes.push_back ({ 43, 0.477f, 0.875, 0.25 });
                p.notes.push_back ({ 43, 0.637f, 1.125, 0.25 });
                p.notes.push_back ({ 43, 0.498f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.549f, 1.625, 0.25 });
                p.notes.push_back ({ 43, 0.482f, 1.875, 0.25 });
                v.push_back ({ "HR Fill 50 Intensity 1", 50, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 43, 0.515f, 0.5, 0.25 });
                p.notes.push_back ({ 48, 0.697f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.452f, 1.5, 0.25 });
                p.notes.push_back ({ 43, 0.609f, 1.625, 0.25 });
                p.notes.push_back ({ 43, 0.651f, 1.75, 0.25 });
                v.push_back ({ "FIll 60 Intensity 1", 60, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 48, 0.591f, 0.125, 0.25 });
                p.notes.push_back ({ 43, 0.565f, 0.625, 0.25 });
                p.notes.push_back ({ 42, 0.555f, 1.0, 0.25 });
                p.notes.push_back ({ 48, 0.566f, 1.125, 0.25 });
                p.notes.push_back ({ 43, 0.555f, 1.5, 0.25 });
                v.push_back ({ "HR FIll 60 Intensity 1", 60, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 38, 0.767f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.512f, 0.5, 0.25 });
                p.notes.push_back ({ 43, 0.541f, 0.875, 0.25 });
                p.notes.push_back ({ 38, 0.693f, 0.875, 0.25 });
                p.notes.push_back ({ 43, 0.659f, 1.375, 0.25 });
                p.notes.push_back ({ 43, 0.542f, 1.625, 0.25 });
                v.push_back ({ "FIll 70 Intensity 1", 70, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 43, 0.345f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.666f, 0.125, 0.25 });
                p.notes.push_back ({ 43, 0.55f, 0.625, 0.25 });
                p.notes.push_back ({ 43, 0.669f, 1.125, 0.25 });
                p.notes.push_back ({ 43, 0.56f, 1.375, 0.25 });
                p.notes.push_back ({ 43, 0.589f, 1.625, 0.25 });
                p.notes.push_back ({ 43, 0.551f, 1.875, 0.25 });
                v.push_back ({ "HR FIll 70 Intensity 1", 70, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 38, 0.389f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.552f, 0.25, 0.25 });
                p.notes.push_back ({ 38, 0.619f, 0.5, 0.25 });
                p.notes.push_back ({ 48, 0.531f, 0.75, 0.25 });
                p.notes.push_back ({ 48, 0.708f, 1.0, 0.25 });
                p.notes.push_back ({ 48, 0.613f, 1.25, 0.25 });
                p.notes.push_back ({ 48, 0.577f, 1.5, 0.25 });
                p.notes.push_back ({ 48, 0.633f, 1.75, 0.25 });
                v.push_back ({ "FIll 80 Intensity 1", 80, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 38, 0.475f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.504f, 0.125, 0.25 });
                p.notes.push_back ({ 48, 0.601f, 0.375, 0.25 });
                p.notes.push_back ({ 48, 0.59f, 0.625, 0.25 });
                p.notes.push_back ({ 43, 0.466f, 0.875, 0.25 });
                p.notes.push_back ({ 43, 0.574f, 1.125, 0.25 });
                p.notes.push_back ({ 42, 0.465f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.469f, 1.625, 0.25 });
                p.notes.push_back ({ 48, 0.575f, 1.75, 0.25 });
                v.push_back ({ "HR FIll 80 Intensity 1", 80, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 43, 0.566f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.691f, 0.25, 0.25 });
                p.notes.push_back ({ 38, 0.669f, 0.5, 0.25 });
                p.notes.push_back ({ 43, 0.679f, 0.75, 0.25 });
                p.notes.push_back ({ 43, 0.452f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.448f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.491f, 1.5, 0.25 });
                p.notes.push_back ({ 43, 0.464f, 1.75, 0.25 });
                v.push_back ({ "FIll 85 Intensity 1", 85, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 48, 0.577f, 0.0, 0.25 });
                p.notes.push_back ({ 48, 0.537f, 0.125, 0.25 });
                p.notes.push_back ({ 43, 0.587f, 0.375, 0.25 });
                p.notes.push_back ({ 43, 0.559f, 0.875, 0.25 });
                p.notes.push_back ({ 43, 0.503f, 1.125, 0.25 });
                p.notes.push_back ({ 43, 0.542f, 1.375, 0.25 });
                p.notes.push_back ({ 43, 0.575f, 1.875, 0.25 });
                v.push_back ({ "HR FIll 85 Intensity 1", 85, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 36, 0.494f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.482f, 0.25, 0.25 });
                p.notes.push_back ({ 43, 0.464f, 0.5, 0.25 });
                p.notes.push_back ({ 43, 0.471f, 0.75, 0.25 });
                p.notes.push_back ({ 43, 0.654f, 1.0, 0.25 });
                p.notes.push_back ({ 42, 0.653f, 1.5, 0.25 });
                p.notes.push_back ({ 48, 0.645f, 1.75, 0.25 });
                v.push_back ({ "Fill 92 Intensity 1", 92, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.656f, 0.0, 0.25 });
                p.notes.push_back ({ 48, 0.663f, 0.125, 0.25 });
                p.notes.push_back ({ 48, 0.577f, 0.625, 0.25 });
                p.notes.push_back ({ 48, 0.624f, 0.875, 0.25 });
                p.notes.push_back ({ 48, 0.654f, 1.125, 0.25 });
                p.notes.push_back ({ 48, 0.581f, 1.375, 0.25 });
                p.notes.push_back ({ 48, 0.659f, 1.625, 0.25 });
                p.notes.push_back ({ 48, 0.574f, 1.875, 0.25 });
                v.push_back ({ "HR Fill 92 Intensity 1", 92, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 38, 0.597f, 0.0, 0.25 });
                p.notes.push_back ({ 38, 0.691f, 0.25, 0.25 });
                p.notes.push_back ({ 43, 0.44f, 0.5, 0.25 });
                p.notes.push_back ({ 43, 0.559f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.449f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.472f, 1.5, 0.25 });
                p.notes.push_back ({ 38, 0.407f, 1.75, 0.25 });
                v.push_back ({ "FIll 100 Intensity 1", 100, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 38, 0.381f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.662f, 0.125, 0.25 });
                p.notes.push_back ({ 43, 0.538f, 0.375, 0.25 });
                p.notes.push_back ({ 43, 0.467f, 0.625, 0.25 });
                p.notes.push_back ({ 43, 0.473f, 0.875, 0.25 });
                p.notes.push_back ({ 43, 0.592f, 1.125, 0.25 });
                p.notes.push_back ({ 43, 0.417f, 1.375, 0.25 });
                p.notes.push_back ({ 43, 0.489f, 1.625, 0.25 });
                p.notes.push_back ({ 43, 0.455f, 1.875, 0.25 });
                v.push_back ({ "HR FIll 100 Intensity 2", 100, std::move (p) });
            }
            // v1.6.1-rc.21 — tom-focused fill bases added at user request
            // ("a few more bases around toms"). Hand-authored MIDI patterns
            // using canonical tom mapping: low=43, mid=45, high=48; snare=38,
            // kick=36, crash=49. All 4-beat patterns @ 16th-grid, isFill=true.
            {
                // 1. "Tom Cascade Roll" — descending high→mid→low 16th roll
                // with snare bookends. Mid-intensity classic rock fill.
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 38, 0.75f, 0.0,  0.25 });
                p.notes.push_back ({ 48, 0.62f, 0.25, 0.25 });
                p.notes.push_back ({ 48, 0.55f, 0.5,  0.25 });
                p.notes.push_back ({ 45, 0.65f, 0.75, 0.25 });
                p.notes.push_back ({ 45, 0.58f, 1.0,  0.25 });
                p.notes.push_back ({ 43, 0.68f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.60f, 1.5,  0.25 });
                p.notes.push_back ({ 38, 0.78f, 1.75, 0.25 });
                p.notes.push_back ({ 36, 0.85f, 2.0,  0.5  });
                p.notes.push_back ({ 49, 0.90f, 2.0,  0.5  });
                v.push_back ({ "Tom Cascade Roll", 55, std::move (p) });
            }
            {
                // 2. "Floor Tom Flam" — doubled low-tom flams with kick on
                // downbeats and snare backbeat. Heavier sludge/metal flavour.
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 36, 0.85f, 0.0,   0.25 });
                p.notes.push_back ({ 43, 0.55f, 0.125, 0.25 }); // grace note
                p.notes.push_back ({ 43, 0.80f, 0.25,  0.25 });
                p.notes.push_back ({ 38, 0.75f, 0.5,   0.25 });
                p.notes.push_back ({ 43, 0.55f, 0.875, 0.25 }); // grace note
                p.notes.push_back ({ 43, 0.82f, 1.0,   0.25 });
                p.notes.push_back ({ 36, 0.78f, 1.25,  0.25 });
                p.notes.push_back ({ 43, 0.60f, 1.375, 0.25 }); // grace note
                p.notes.push_back ({ 43, 0.85f, 1.5,   0.25 });
                p.notes.push_back ({ 38, 0.78f, 1.75,  0.25 });
                p.notes.push_back ({ 43, 0.65f, 1.875, 0.25 }); // grace note
                p.notes.push_back ({ 43, 0.88f, 2.0,   0.5  });
                p.notes.push_back ({ 49, 0.88f, 2.0,   0.5  });
                v.push_back ({ "Floor Tom Flam", 75, std::move (p) });
            }
            {
                // 3. "Tom Triplet Roll" — 16th-note triplet feel across all
                // three toms. 12 evenly-spaced tom hits with crescendo.
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                const double tripletStep = 4.0 / 12.0; // 12 triplet 8ths in 4 beats
                const int    pitches[12] = { 48, 48, 45, 45, 45, 43, 43, 43, 43, 43, 43, 38 };
                for (int i = 0; i < 12; ++i)
                {
                    const float vel = 0.45f + (float) i * 0.04f; // crescendo 0.45 → 0.89
                    p.notes.push_back ({ pitches[i], vel, (double) i * tripletStep, 0.25 });
                }
                p.notes.push_back ({ 36, 0.92f, 3.5, 0.5 });
                p.notes.push_back ({ 49, 0.92f, 3.5, 0.5 });
                v.push_back ({ "Tom Triplet Roll", 65, std::move (p) });
            }
            {
                // 4. "Tom-to-Snare Climb" — ascending low→mid→high tom run
                // with snare doubles, ending on a kick+crash stab. Light to
                // mid intensity build.
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 43, 0.55f, 0.0,  0.25 });
                p.notes.push_back ({ 43, 0.60f, 0.25, 0.25 });
                p.notes.push_back ({ 45, 0.62f, 0.5,  0.25 });
                p.notes.push_back ({ 45, 0.66f, 0.75, 0.25 });
                p.notes.push_back ({ 48, 0.70f, 1.0,  0.25 });
                p.notes.push_back ({ 48, 0.74f, 1.25, 0.25 });
                p.notes.push_back ({ 38, 0.72f, 1.5,  0.25 });
                p.notes.push_back ({ 38, 0.78f, 1.75, 0.25 });
                p.notes.push_back ({ 38, 0.80f, 2.0,  0.25 });
                p.notes.push_back ({ 38, 0.83f, 2.25, 0.25 });
                p.notes.push_back ({ 36, 0.88f, 2.5,  0.5  });
                p.notes.push_back ({ 49, 0.88f, 2.5,  0.5  });
                v.push_back ({ "Tom-to-Snare Climb", 45, std::move (p) });
            }
            {
                // 5. "Double Tom Stab" — punctuated low-tom doubles separated
                // by hat 8ths. Pop / new-wave flavour, mid-low intensity.
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.38f, 0.0,  0.25 });
                p.notes.push_back ({ 43, 0.78f, 0.25, 0.25 });
                p.notes.push_back ({ 43, 0.72f, 0.375, 0.25 });
                p.notes.push_back ({ 42, 0.36f, 0.5,  0.25 });
                p.notes.push_back ({ 45, 0.78f, 0.75, 0.25 });
                p.notes.push_back ({ 45, 0.72f, 0.875, 0.25 });
                p.notes.push_back ({ 42, 0.36f, 1.0,  0.25 });
                p.notes.push_back ({ 48, 0.80f, 1.25, 0.25 });
                p.notes.push_back ({ 48, 0.74f, 1.375, 0.25 });
                p.notes.push_back ({ 38, 0.82f, 1.5,  0.25 });
                p.notes.push_back ({ 43, 0.78f, 1.75, 0.25 });
                p.notes.push_back ({ 43, 0.70f, 1.875, 0.25 });
                p.notes.push_back ({ 36, 0.88f, 2.0,  0.5  });
                p.notes.push_back ({ 49, 0.88f, 2.0,  0.5  });
                v.push_back ({ "Double Tom Stab", 35, std::move (p) });
            }
            return v;
        }();
        return kFills;
    }
}
