// v1.6.1-rc.9 — GENERATED by tools/analyze_user_fills.py.
// DO NOT EDIT: re-run the analyzer to update.
// Source of truth = tools/user_fills/*.wav (20 intensity-graded
// drum fills supplied by the user). Each fill is parsed into our
// 8-lane canonical MIDI (kick=36 snare=38 hat=42 lowTom=43
// highTom=48 lcrash=49 ride=51 rcrash=57) and exposed as the
// fill library the FILL cycler rotates through and the auto-fill
// scheduler drops on bar 8 of every 8-bar phrase.
#pragma once

#include "MidiPattern.h"

#include <string_view>
#include <vector>

namespace aidrum
{
    struct BuiltInFill
    {
        std::string_view name;
        int             intensity;  // 10..100
        MidiPattern     pattern;
    };

    inline const std::vector<BuiltInFill>& fillLibrary()
    {
        static const std::vector<BuiltInFill> kFills = [] {
            std::vector<BuiltInFill> v;
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.328f, 0.0, 0.25 });
                p.notes.push_back ({ 38, 0.522f, 0.5, 0.25 });
                p.notes.push_back ({ 42, 0.462f, 0.75, 0.25 });
                p.notes.push_back ({ 48, 0.632f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.476f, 1.5, 0.25 });
                v.push_back ({ "Fill 10 Intensity 1", 10, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 36, 0.492f, 0.0, 0.25 });
                p.notes.push_back ({ 38, 0.422f, 0.25, 0.25 });
                p.notes.push_back ({ 43, 0.516f, 0.5, 0.25 });
                p.notes.push_back ({ 48, 0.661f, 0.75, 0.25 });
                p.notes.push_back ({ 43, 0.53f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.439f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.507f, 1.5, 0.25 });
                p.notes.push_back ({ 42, 0.658f, 1.75, 0.25 });
                v.push_back ({ "HR Fill 10 Intensity 1", 10, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.33f, 0.0, 0.25 });
                p.notes.push_back ({ 42, 0.691f, 0.5, 0.25 });
                p.notes.push_back ({ 43, 0.532f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.456f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.502f, 1.5, 0.25 });
                p.notes.push_back ({ 36, 0.487f, 1.75, 0.25 });
                v.push_back ({ "Fill 20 Intensity 1", 20, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.596f, 0.25, 0.25 });
                p.notes.push_back ({ 42, 0.585f, 0.75, 0.25 });
                p.notes.push_back ({ 43, 0.581f, 1.25, 0.25 });
                p.notes.push_back ({ 38, 0.547f, 1.75, 0.25 });
                v.push_back ({ "HR Fill 20 Intensity 1", 20, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.33f, 0.0, 0.25 });
                p.notes.push_back ({ 42, 0.693f, 0.5, 0.25 });
                p.notes.push_back ({ 43, 0.534f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.435f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.509f, 1.5, 0.25 });
                p.notes.push_back ({ 36, 0.472f, 1.75, 0.25 });
                v.push_back ({ "Fill 30 Intensity 1", 30, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.646f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.678f, 0.125, 0.25 });
                p.notes.push_back ({ 43, 0.503f, 0.375, 0.25 });
                p.notes.push_back ({ 48, 0.543f, 0.625, 0.25 });
                p.notes.push_back ({ 43, 0.651f, 1.125, 0.25 });
                p.notes.push_back ({ 48, 0.562f, 1.625, 0.25 });
                p.notes.push_back ({ 38, 0.58f, 1.75, 0.25 });
                v.push_back ({ "HR Fill 30 Intensity 1", 30, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.335f, 0.25, 0.25 });
                p.notes.push_back ({ 48, 0.584f, 0.75, 0.25 });
                p.notes.push_back ({ 43, 0.452f, 1.25, 0.25 });
                p.notes.push_back ({ 36, 0.445f, 1.5, 0.25 });
                p.notes.push_back ({ 38, 0.564f, 1.75, 0.25 });
                v.push_back ({ "FIll 40 Intensity 1", 40, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.603f, 0.125, 0.25 });
                p.notes.push_back ({ 42, 0.578f, 0.5, 0.25 });
                p.notes.push_back ({ 38, 0.579f, 0.625, 0.25 });
                p.notes.push_back ({ 43, 0.556f, 1.125, 0.25 });
                p.notes.push_back ({ 43, 0.56f, 1.5, 0.25 });
                p.notes.push_back ({ 43, 0.589f, 1.625, 0.25 });
                p.notes.push_back ({ 38, 0.587f, 1.75, 0.25 });
                v.push_back ({ "HR FIll 40 Intensity 1", 40, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 43, 0.456f, 0.0, 0.25 });
                p.notes.push_back ({ 36, 0.533f, 0.5, 0.25 });
                p.notes.push_back ({ 36, 0.506f, 0.75, 0.25 });
                p.notes.push_back ({ 43, 0.632f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.516f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.605f, 1.5, 0.25 });
                p.notes.push_back ({ 38, 0.589f, 1.75, 0.25 });
                v.push_back ({ "Fill 50 Intensity 1", 50, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 43, 0.591f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.48f, 0.375, 0.25 });
                p.notes.push_back ({ 43, 0.551f, 0.625, 0.25 });
                p.notes.push_back ({ 43, 0.477f, 0.875, 0.25 });
                p.notes.push_back ({ 43, 0.637f, 1.125, 0.25 });
                p.notes.push_back ({ 43, 0.498f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.549f, 1.625, 0.25 });
                p.notes.push_back ({ 43, 0.482f, 1.875, 0.25 });
                v.push_back ({ "HR Fill 50 Intensity 1", 50, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 43, 0.515f, 0.5, 0.25 });
                p.notes.push_back ({ 48, 0.697f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.452f, 1.5, 0.25 });
                p.notes.push_back ({ 43, 0.609f, 1.625, 0.25 });
                p.notes.push_back ({ 43, 0.651f, 1.75, 0.25 });
                v.push_back ({ "FIll 60 Intensity 1", 60, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 48, 0.591f, 0.125, 0.25 });
                p.notes.push_back ({ 43, 0.565f, 0.625, 0.25 });
                p.notes.push_back ({ 42, 0.555f, 1.0, 0.25 });
                p.notes.push_back ({ 48, 0.566f, 1.125, 0.25 });
                p.notes.push_back ({ 43, 0.555f, 1.5, 0.25 });
                v.push_back ({ "HR FIll 60 Intensity 1", 60, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 38, 0.767f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.512f, 0.5, 0.25 });
                p.notes.push_back ({ 43, 0.541f, 0.875, 0.25 });
                p.notes.push_back ({ 38, 0.693f, 0.875, 0.25 });
                p.notes.push_back ({ 43, 0.659f, 1.375, 0.25 });
                p.notes.push_back ({ 43, 0.542f, 1.625, 0.25 });
                v.push_back ({ "FIll 70 Intensity 1", 70, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 43, 0.345f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.666f, 0.125, 0.25 });
                p.notes.push_back ({ 43, 0.55f, 0.625, 0.25 });
                p.notes.push_back ({ 43, 0.669f, 1.125, 0.25 });
                p.notes.push_back ({ 43, 0.56f, 1.375, 0.25 });
                p.notes.push_back ({ 43, 0.589f, 1.625, 0.25 });
                p.notes.push_back ({ 43, 0.551f, 1.875, 0.25 });
                v.push_back ({ "HR FIll 70 Intensity 1", 70, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 38, 0.389f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.552f, 0.25, 0.25 });
                p.notes.push_back ({ 38, 0.619f, 0.5, 0.25 });
                p.notes.push_back ({ 48, 0.531f, 0.75, 0.25 });
                p.notes.push_back ({ 48, 0.708f, 1.0, 0.25 });
                p.notes.push_back ({ 48, 0.613f, 1.25, 0.25 });
                p.notes.push_back ({ 48, 0.577f, 1.5, 0.25 });
                p.notes.push_back ({ 48, 0.633f, 1.75, 0.25 });
                v.push_back ({ "FIll 80 Intensity 1", 80, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 38, 0.475f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.504f, 0.125, 0.25 });
                p.notes.push_back ({ 48, 0.601f, 0.375, 0.25 });
                p.notes.push_back ({ 48, 0.59f, 0.625, 0.25 });
                p.notes.push_back ({ 43, 0.466f, 0.875, 0.25 });
                p.notes.push_back ({ 43, 0.574f, 1.125, 0.25 });
                p.notes.push_back ({ 42, 0.465f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.469f, 1.625, 0.25 });
                p.notes.push_back ({ 48, 0.575f, 1.75, 0.25 });
                v.push_back ({ "HR FIll 80 Intensity 1", 80, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 43, 0.566f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.691f, 0.25, 0.25 });
                p.notes.push_back ({ 38, 0.669f, 0.5, 0.25 });
                p.notes.push_back ({ 43, 0.679f, 0.75, 0.25 });
                p.notes.push_back ({ 43, 0.452f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.448f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.491f, 1.5, 0.25 });
                p.notes.push_back ({ 43, 0.464f, 1.75, 0.25 });
                v.push_back ({ "FIll 85 Intensity 1", 85, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 48, 0.577f, 0.0, 0.25 });
                p.notes.push_back ({ 48, 0.537f, 0.125, 0.25 });
                p.notes.push_back ({ 43, 0.587f, 0.375, 0.25 });
                p.notes.push_back ({ 43, 0.559f, 0.875, 0.25 });
                p.notes.push_back ({ 43, 0.503f, 1.125, 0.25 });
                p.notes.push_back ({ 43, 0.542f, 1.375, 0.25 });
                p.notes.push_back ({ 43, 0.575f, 1.875, 0.25 });
                v.push_back ({ "HR FIll 85 Intensity 1", 85, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 36, 0.494f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.482f, 0.25, 0.25 });
                p.notes.push_back ({ 43, 0.464f, 0.5, 0.25 });
                p.notes.push_back ({ 43, 0.471f, 0.75, 0.25 });
                p.notes.push_back ({ 43, 0.654f, 1.0, 0.25 });
                p.notes.push_back ({ 42, 0.653f, 1.5, 0.25 });
                p.notes.push_back ({ 48, 0.645f, 1.75, 0.25 });
                v.push_back ({ "Fill 92 Intensity 1", 92, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 42, 0.656f, 0.0, 0.25 });
                p.notes.push_back ({ 48, 0.663f, 0.125, 0.25 });
                p.notes.push_back ({ 48, 0.577f, 0.625, 0.25 });
                p.notes.push_back ({ 48, 0.624f, 0.875, 0.25 });
                p.notes.push_back ({ 48, 0.654f, 1.125, 0.25 });
                p.notes.push_back ({ 48, 0.581f, 1.375, 0.25 });
                p.notes.push_back ({ 48, 0.659f, 1.625, 0.25 });
                p.notes.push_back ({ 48, 0.574f, 1.875, 0.25 });
                v.push_back ({ "HR Fill 92 Intensity 1", 92, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 38, 0.597f, 0.0, 0.25 });
                p.notes.push_back ({ 38, 0.691f, 0.25, 0.25 });
                p.notes.push_back ({ 43, 0.44f, 0.5, 0.25 });
                p.notes.push_back ({ 43, 0.559f, 1.0, 0.25 });
                p.notes.push_back ({ 43, 0.449f, 1.25, 0.25 });
                p.notes.push_back ({ 43, 0.472f, 1.5, 0.25 });
                p.notes.push_back ({ 38, 0.407f, 1.75, 0.25 });
                v.push_back ({ "FIll 100 Intensity 1", 100, std::move (p) });
            }
            {
                MidiPattern p;
                p.lengthInBeats = 4.00;
                p.isFill = true;
                p.notes.push_back ({ 38, 0.381f, 0.0, 0.25 });
                p.notes.push_back ({ 43, 0.662f, 0.125, 0.25 });
                p.notes.push_back ({ 43, 0.538f, 0.375, 0.25 });
                p.notes.push_back ({ 43, 0.467f, 0.625, 0.25 });
                p.notes.push_back ({ 43, 0.473f, 0.875, 0.25 });
                p.notes.push_back ({ 43, 0.592f, 1.125, 0.25 });
                p.notes.push_back ({ 43, 0.417f, 1.375, 0.25 });
                p.notes.push_back ({ 43, 0.489f, 1.625, 0.25 });
                p.notes.push_back ({ 43, 0.455f, 1.875, 0.25 });
                v.push_back ({ "HR FIll 100 Intensity 2", 100, std::move (p) });
            }
            return v;
        }();
        return kFills;
    }
}
