// v1.6.0 — GENERATED by tools/analyze_starter_grooves.py (SoCal pass).
// DO NOT EDIT: re-run the analyzer to update.
// Source of truth = tools/socal_grooves/*.wav.

#pragma once

#include "StarterGrooves.generated.h"

namespace aidrum
{
    inline const std::vector<StarterGroove>& socalGrooveLibrary()
    {
        static const std::vector<StarterGroove> kLibrary = []
        {
            std::vector<StarterGroove> g;
            {
                StarterGroove sg;
                sg.name = "SOCAL";
                sg.bpm = 110.0;
                sg.lengthBeats = 8.0;
                sg.pattern.lengthInBeats = 8.0;
                sg.pattern.notes.push_back ({ 38, 0.609f, 0.49999999999999994, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.532f, 1.2499999999999998, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.61f, 1.4999999999999998, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.529f, 2.2499999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.613f, 2.4999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.549f, 2.9999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.615f, 3.4999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.549f, 3.9999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.608f, 4.499999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.604f, 5.5, 0.12 });
                sg.pattern.notes.push_back ({ 51, 0.416f, 5.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.532f, 6.249999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.636f, 6.499999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.549f, 6.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.607f, 7.499999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.552f, 7.999999999999999, 0.12 });
                g.push_back (std::move (sg));
            }
            {
                StarterGroove sg;
                sg.name = "SOCAL  1";
                sg.bpm = 112.0;
                sg.lengthBeats = 8.0;
                sg.pattern.lengthInBeats = 8.0;
                sg.pattern.notes.push_back ({ 51, 0.369f, 0.5, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.662f, 1.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.577f, 2.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.558f, 2.5, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.703f, 3.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.581f, 4.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.373f, 4.5, 0.12 });
                sg.pattern.notes.push_back ({ 49, 0.658f, 5.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.577f, 6.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.576f, 6.5, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.661f, 7.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.543f, 7.499999999999999, 0.12 });
                g.push_back (std::move (sg));
            }
            {
                StarterGroove sg;
                sg.name = "SOCAL  2";
                sg.bpm = 110.0;
                sg.lengthBeats = 8.0;
                sg.pattern.lengthInBeats = 8.0;
                sg.pattern.notes.push_back ({ 38, 0.489f, 0.24999999999999997, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.612f, 0.9999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.593f, 1.4999999999999998, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.494f, 1.7499999999999998, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.601f, 1.9999999999999998, 0.12 });
                sg.pattern.notes.push_back ({ 49, 0.611f, 2.9999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.603f, 3.9999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 49, 0.613f, 4.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.588f, 5.5, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.596f, 5.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.513f, 6.249999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.607f, 6.749999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.606f, 6.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.601f, 7.249999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.554f, 7.749999999999998, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.614f, 7.999999999999999, 0.12 });
                g.push_back (std::move (sg));
            }
            {
                StarterGroove sg;
                sg.name = "SOCAL  3";
                sg.bpm = 110.0;
                sg.lengthBeats = 8.0;
                sg.pattern.lengthInBeats = 8.0;
                sg.pattern.notes.push_back ({ 38, 0.614f, 0.9999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.612f, 1.9999999999999998, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.551f, 2.4999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.608f, 2.9999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.554f, 3.4999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.635f, 3.9999999999999996, 0.12 });
                // v1.6.1-rc.24 — middle snare (beat 4.999) replaced with
                // low tom (note 41) so the bar-2 backbeat run no longer
                // strings 3 consecutive snares (3.999 / 4.999 / 5.999).
                // Per user direction: kill 3+ consecutive snare hits +
                // toms must always be active.
                sg.pattern.notes.push_back ({ 41, 0.604f, 4.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.604f, 5.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.547f, 6.499999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.613f, 6.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.547f, 7.499999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.605f, 7.999999999999999, 0.12 });
                g.push_back (std::move (sg));
            }
            {
                StarterGroove sg;
                sg.name = "SOCAL  4";
                sg.bpm = 110.0;
                sg.lengthBeats = 8.0;
                sg.pattern.lengthInBeats = 8.0;
                sg.pattern.notes.push_back ({ 36, 0.371f, 0.49999999999999994, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.662f, 0.9999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.664f, 1.4999999999999998, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.576f, 2.4999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.705f, 2.9999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.591f, 3.9999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 51, 0.374f, 4.499999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 49, 0.703f, 4.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.579f, 5.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.552f, 6.499999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.662f, 6.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.542f, 7.499999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.573f, 7.999999999999999, 0.12 });
                g.push_back (std::move (sg));
            }
            {
                StarterGroove sg;
                sg.name = "SOCAL  5";
                sg.bpm = 112.0;
                sg.lengthBeats = 8.0;
                sg.pattern.lengthInBeats = 8.0;
                sg.pattern.notes.push_back ({ 51, 0.369f, 0.5, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.662f, 1.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.581f, 1.5, 0.12 });
                sg.pattern.notes.push_back ({ 51, 0.386f, 2.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.576f, 2.5, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.703f, 3.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.581f, 4.0, 0.12 });
                sg.pattern.notes.push_back ({ 42, 0.374f, 4.5, 0.12 });
                sg.pattern.notes.push_back ({ 49, 0.705f, 5.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.572f, 5.5, 0.12 });
                sg.pattern.notes.push_back ({ 51, 0.387f, 6.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.578f, 6.5, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.663f, 7.0, 0.12 });
                g.push_back (std::move (sg));
            }
            {
                StarterGroove sg;
                sg.name = "SOCAL  6";
                sg.bpm = 110.0;
                sg.lengthBeats = 8.0;
                sg.pattern.lengthInBeats = 8.0;
                sg.pattern.notes.push_back ({ 36, 0.535f, 0.0, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.667f, 0.9999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.561f, 1.9999999999999998, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.667f, 2.4999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.558f, 3.4999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.584f, 3.9999999999999996, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.716f, 4.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.557f, 5.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.561f, 6.499999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.67f, 6.999999999999999, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.584f, 7.999999999999999, 0.12 });
                g.push_back (std::move (sg));
            }
            {
                StarterGroove sg;
                sg.name = "SOCAL  9";
                sg.bpm = 112.0;
                sg.lengthBeats = 8.0;
                sg.pattern.lengthInBeats = 8.0;
                sg.pattern.notes.push_back ({ 36, 0.371f, 0.5, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.662f, 1.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.578f, 1.5, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.582f, 2.0, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.706f, 2.5, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.549f, 3.5, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.581f, 4.0, 0.12 });
                sg.pattern.notes.push_back ({ 51, 0.372f, 4.5, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.658f, 5.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.577f, 6.0, 0.12 });
                sg.pattern.notes.push_back ({ 36, 0.551f, 6.5, 0.12 });
                sg.pattern.notes.push_back ({ 38, 0.662f, 7.0, 0.12 });
                g.push_back (std::move (sg));
            }
            return g;
        }();
        return kLibrary;
    }
}
